install:
#  - set QTDIR=C:\Qt\5.5\msvc2013_64
  - set QTDIR=C:\Qt\5.5\mingw492_32
  - set PATH=%PATH%;%QTDIR%\bin
#  - set PATH=%PATH%;C:\MinGW\bin
  - set PATH=%PATH%;C:\Qt\Tools\mingw492_32
  - set QMAKEFEATURES=C:\projects\freq\features
  - git submodule init
  - git submodule update --depth 1 3rdparty\windows
  - dir /s /b /a:d C:\Qt\5.5
  #- dir /s /b /a:d C:\MinGW
  - echo %PATH%
build_script:
  - cd quick
  - qmake -r -Wall -spec win32-g++
  - mingw32-make
